// Auth action types
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGOUT = 'LOGOUT';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const AUTH_ERROR = 'AUTH_ERROR';
export const SET_USER = 'SET_USER';
export const AUTH_LOADING = 'AUTH_LOADING';

// User address action types
export const GET_ADDRESS = 'GET_ADDRESS';
export const ADD_ADDRESS = 'ADD_ADDRESS';
export const UPDATE_ADDRESS = 'UPDATE_ADDRESS';
export const DELETE_ADDRESS = 'DELETE_ADDRESS';
export const ADDRESS_ERROR = 'ADDRESS_ERROR';
export const GET_COUNTRIES = 'GET_COUNTRIES';
export const GET_CITIES_BY_COUNTRY = 'GET_CITIES_BY_COUNTRY';

// User order action types
export const GET_USER_ORDERS = 'GET_USER_ORDERS';
export const GET_USER_ORDERS_ERROR = 'GET_USER_ORDERS_ERROR';

// User return action types
export const GET_USER_RETURNS = 'GET_USER_RETURNS';
export const GET_USER_RETURNS_ERROR = 'GET_USER_RETURNS_ERROR';

// User wishlist action types
export const GET_WISHLIST_ITEMS = 'GET_WISHLIST_ITEMS';
export const GET_WISHLIST_ITEMS_ERROR = 'GET_WISHLIST_ITEMS_ERROR';
export const REMOVE_FROM_WISHLIST = 'REMOVE_FROM_WISHLIST';
export const CLEAR_WISHLIST = 'CLEAR_WISHLIST';

// User cart action types
export const GET_CART_ITEMS = 'GET_CART_ITEMS';
export const GET_CART_ITEMS_ERROR = 'GET_CART_ITEMS_ERROR';
export const UPDATE_CART_QUANTITY = 'UPDATE_CART_QUANTITY';
export const UPDATE_CART_QUANTITY_ERROR = 'UPDATE_CART_QUANTITY_ERROR';
export const REMOVE_CART_ITEM = 'REMOVE_CART_ITEM';
export const REMOVE_CART_ITEM_ERROR = 'REMOVE_CART_ITEM_ERROR';
export const CLEAR_CART = 'CLEAR_CART';
export const CLEAR_CART_ERROR = 'CLEAR_CART_ERROR';

// User reviews action types
export const GET_USER_REVIEWS = 'GET_USER_REVIEWS';
export const GET_USER_REVIEWS_ERROR = 'GET_USER_REVIEWS_ERROR';
export const EDIT_USER_REVIEW = 'EDIT_USER_REVIEW';
export const EDIT_USER_REVIEW_ERROR = 'EDIT_USER_REVIEW_ERROR';
export const DELETE_USER_REVIEW = 'DELETE_USER_REVIEW';
export const DELETE_USER_REVIEW_ERROR = 'DELETE_USER_REVIEW_ERROR';

// Product action types
export const GET_PRODUCTS = 'GET_PRODUCTS';
export const GET_PRODUCTS_ERROR = 'GET_PRODUCTS_ERROR';

// Categories action types
export const GET_CATEGORIES = 'GET_CATEGORIES';
export const GET_CATEGORIES_ERROR = 'GET_CATEGORIES_ERROR';
export const GET_SUBCATEGORIES = 'GET_SUBCATEGORIES';
export const GET_SUBCATEGORIES_ERROR = 'GET_SUBCATEGORIES_ERROR';
export const GET_SUBCATEGORIES_BY_CATEGORY = 'GET_SUBCATEGORIES_BY_CATEGORY';
export const GET_SUBCATEGORIES_BY_CATEGORY_ERROR = 'GET_SUBCATEGORIES_BY_CATEGORY_ERROR';
export const GET_SUBSUBCATEGORIES_BY_SUBCATEGORY = 'GET_SUBSUBCATEGORIES_BY_SUBCATEGORY';
export const GET_SUBSUBCATEGORIES_BY_SUBCATEGORY_ERROR = 'GET_SUBSUBCATEGORIES_BY_SUBCATEGORY_ERROR';

// Slideshow action types
export const GET_SLIDESHOWS = 'GET_SLIDESHOWS';
export const GET_SLIDESHOWS_ERROR = 'GET_SLIDESHOWS_ERROR';

// Dashboard tables action types
export const GET_USERS = 'GET_USERS';
export const GET_USERS_ERROR = 'GET_USERS_ERROR';
export const GET_ROLES = 'GET_ROLES';
export const GET_ROLES_ERROR = 'GET_ROLES_ERROR';
export const GET_REVIEWS = 'GET_REVIEWS';
export const GET_REVIEWS_ERROR = 'GET_REVIEWS_ERROR';
export const GET_ORDERS = 'GET_ORDERS';
export const GET_ORDERS_ERROR = 'GET_ORDERS_ERROR';
export const GET_RETURNS = 'GET_RETURNS';
export const GET_RETURNS_ERROR = 'GET_RETURNS_ERROR';
export const GET_FAQS = 'GET_FAQS';
export const GET_FAQS_ERROR = 'GET_FAQS_ERROR';
export const GET_CONTACTS = 'GET_CONTACTS';
export const GET_CONTACTS_ERROR = 'GET_CONTACTS_ERROR';
export const GET_SUBSUBCATEGORIES = 'GET_SUBSUBCATEGORIES';
export const GET_SUBSUBCATEGORIES_ERROR = 'GET_SUBSUBCATEGORIES_ERROR';
export const GET_CITIES = 'GET_CITIES';
export const GET_CITIES_ERROR = 'GET_CITIES_ERROR';
export const GET_ADDRESSES = 'GET_ADDRESSES';
export const GET_ADDRESSES_ERROR = 'GET_ADDRESSES_ERROR';
export const GET_SUPPLIERS = 'GET_SUPPLIERS';
export const GET_SUPPLIERS_ERROR = 'GET_SUPPLIERS_ERROR';